# Generated by Django 5.0.6 on 2025-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('franchise_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('logo', models.ImageField(null=True, upload_to='images/team-logo')),
                ('conference', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=50, null=True)),
                ('start_season', models.IntegerField(null=True)),
                ('final_season', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('venue', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
