# Generated by Django 5.0.6 on 2025-01-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamstats', '0002_remove_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
